### ISSUE TITLE
Error on PG Parser extension update on QGIS 3.34.8 Winx64

### ISSUE THREAD

**Issue by ponceta** [opengisch/pgserviceparser#36]
```
Impossible de charger l'extension 'pg_service_parser' 

ModuleNotFoundError: No module named 'pgserviceparser' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\pg_service_parser\__init__.py", line 1, in 
    from .pg_service_parser_plugin import PgServiceParserPlugin
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\pg_service_parser\pg_service_parser_plugin.py", line 6, in 
    from pg_service_parser.gui.dlg_pg_service import PgServiceDialog
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\pg_service_parser\gui\dlg_pg_service.py", line 10, in 
    from pg_service_parser.core.pg_service_parser_wrapper import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\pg_service_parser\core\pg_service_parser_wrapper.py", line 4, in 
    from pg_service_parser.libs import pgserviceparser
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins\pg_service_parser\libs\pgserviceparser\__init__.py", line 9, in 
    from pgserviceparser.exceptions import ServiceFileNotFound, ServiceNotFound
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pgserviceparser'


Version de Python : 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.8-Prizren Prizren, 91642333 

Chemin Python :
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\pulpoar/python
C:\Users\pulpoar\AppData\Roaming\QGIS\QGIS3\profiles\pulpoar\python\plugins\qfieldsync\libqfieldsync.whl
```

**Comment by gacarrillor** [comment]
Thank you @ponceta for the report. If it's related to the plugin, next time you can create it directly in this repo: https://github.com/opengisch/qgis-pg-service-parser-plugin
